myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('searchPosts/', include('searchPosts.urls')),
    path('admin/', admin.site.urls)
]

searchPosts/urls.py
from django.urls import path
from . import views

app_name = "searchPosts"
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search')
]

searchPosts/models.py
from django.db import models


# Create your models here.

class PostData(models.Model):
    language = models.CharField('语言', max_length=30)
    city = models.CharField('城市', max_length=20)
    company = models.CharField('公司', max_length=30)
    scale = models.CharField('规模', max_length=15)
    xueli = models.CharField('学历', max_length=10)
    lat = models.FloatField('纬度', max_length=15)
    longitude = models.FloatField('经度', max_length=15)
    post = models.CharField('职位', max_length=20)
    salary = models.CharField('薪资', max_length=10)
    salary_min = models.IntegerField('最少薪资', default=0)
    # salary_max = models.IntegerField('最多薪资', max_length=10)
    exp = models.CharField('工作经验', max_length=10)
    exp_min = models.IntegerField('最低工作经验', default=0)
    welfare = models.CharField('福利', max_length=30)

searchPosts/views.py
from django.shortcuts import render
from .models import PostData
# Create your views here.




def index(request):
    """
    首页路由
    :param request:
    :return:
    """
    return render(request, 'searchPosts/index.html')


def search(request):
    """
    搜索路由
    :param request:
    :return:
    """
    # 判断请求是否为post请求
    if request.method == "POST":
        search_where = dict()
        # 将用户提交得数据取出
        language = request.POST["language"]
        city = request.POST["city"]
        xueli = request.POST["xueli"]
        salary_min = request.POST["salary_min"]
        exp_min = request.POST["exp_min"]
        # 判断提交信息是否为空？空不做操作
        if language:
            search_where["language"] = language.capitalize()
        if city:
            search_where["city"] = city
        if xueli:
            search_where["xueli"] = xueli
        if salary_min:
            screen = PostData.objects.filter(salary_min__gte=salary_min)
        if exp_min:
            # search_where["exp_min"] = exp_min
            if salary_min:
                screen = screen.filter(exp_min__lte=exp_min)
            else:
                screen = PostData.objects.filter(exp_min__lte=exp_min)
        if language or city or xueli or salary_min or exp_min:
            # del search_where["salary_min"]
            # del search_where["exp_min"]
            if exp_min or salary_min:
                search_info = screen.filter(**search_where)
            else:
                search_info = PostData.objects.filter(**search_where)
            # search_info = PostData.objects.filter(**search_where)
            if len(search_info):
                context = {
                    "status": 200,
                    "fieds": ["语言", "城市", "公司", "规模", "学历", "纬度", "经度", "职位", "薪资", "经验", "福利"],
                    "search_info": search_info
                }
            else:
                context = {
                    "status": 404,
                    "fieds": "未找到合适职位"
                }
        else:
            context = {
                "status": 000,
                "fieds": "请输入查询条件",
                "search_info": None
            }
            print(len(search_where))
        return render(request, 'searchPosts/result.html', context)

searchPosts/templates/searchPosts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}home{% endblock %}</title>
</head>
<body>
<div id="search_posts">
  <h1 style="text-align: center">欢迎使用本工具</h1>
  <form method="post" action="{% url 'searchPosts:search' %}">
    {% csrf_token %}
    编程语言:<input type="text" name="language">
    工作城市:<input type="text" name="city">
    学历:<input type="text" name="xueli">
    最低工资:<input type="text" name="salary_min">
    工作经验最低要求:<input type="text" name="exp_min">
    <button type="submit">查询</button>
    <br/>
    <br/>
  </form>
  <div id="search_result">
    <table border="1" style="text-align: center; margin-right: auto; margin-left: auto">
      {% block table %}{% endblock %}
    </table>
  </div>
</div>
</body>
</html>

searchPosts/templates/searchPosts/result.html
{% extends "searchPosts/index.html" %}
{% block title %}result{% endblock %}
{% block table %}
  {% if status == 200 %}
    <tr>
        {% for fied in  fieds %}
          <th>{{ fied }}</th>
        {% endfor %}
    </tr>
  {% endif %}
  {% if status == 404 %}
    <h3 style="text-align: center">{{ fieds }}</h3>
  {% endif %}
  {% if status == 000 %}
    <h3 style="text-align: center">{{ fieds }}</h3>
  {% endif %}

  {% for info in search_info %}
    <tr>
      <td>{{ info.language }}</td>
      <td>{{ info.city }}</td>
      <td>{{ info.company }}</td>
      <td>{{ info.scale }}</td>
      <td>{{ info.xueli }}</td>
      <td>{{ info.lat }}</td>
      <td>{{ info.longitude }}</td>
      <td>{{ info.post }}</td>
      <td>{{ info.salary }}</td>
      <td>{{ info.exp }}</td>
      <td>{{ info.welfare }}</td>
    </tr>
  {% endfor %}



{% endblock %}